In [2]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
file = 'Toda_201911.txt'

num_features = 10

feature_cols = [str(f_index) for f_index in range(1, num_features+1)]

df = pd.read_csv(file, sep=" ", header=None)
df.drop(columns=df.columns[[1,2,3,5,7,9,11,13,15,17,19,21]], axis=1, inplace=True)  # remove redundant keys
#print(df)
#print(self.num_features, len(df.columns))
#assert self.num_features == len(df.columns) - 2

#for c in range(1, self.num_features + 2):  # remove keys per column from key:value
#    df.iloc[:, c] = df.iloc[:, c].apply(lambda x: x.split(":")[1])

df.columns = ['rele_truth', 'teiban', 'player_age', 'player_weight', 'player_level', 'all_winrate', 'all_2rate', 
          'local_winrate', 'local_2rate', 'motor_2rate', 'boat_2rate'] #+ feature_cols #+ ['#docid', 'inc', 'prob']

#if self.data_id in MSLETOR_SEMI and self.data_dict['unknown_as_zero']:
#    self.df[self.df[self.feature_cols] < 0] = 0

for c in ['rele_truth', 'teiban', 'player_age', 'player_weight', 'player_level', 'all_winrate', 'all_2rate', 
          'local_winrate', 'local_2rate', 'motor_2rate', 'boat_2rate']:# + feature_cols:
    df[c] = df[c].astype(np.float32)

#df['rele_binary'] = (df['rele_truth'] > 0).astype(np.float32)  # additional binarized column for later filtering

print(pd.DataFrame(df))

      rele_truth  teiban  player_age  player_weight  player_level  \
0            3.0     1.0        26.0           50.0           3.0
1            2.0     2.0        55.0           50.0           2.0
2            1.0     3.0        57.0           50.0           2.0
3            4.0     4.0        42.0           47.0           1.0
4            5.0     5.0        26.0           48.0           2.0
5            0.0     6.0        22.0           44.0           2.0
6            5.0     1.0        40.0           52.0           2.0
7            2.0     2.0        47.0           53.0           2.0
8            0.0     3.0        25.0           52.0           2.0
9            4.0     4.0        40.0           53.0           0.0
10           1.0     5.0        46.0           58.0           2.0
11           3.0     6.0        31.0           52.0           2.0
12           3.0     1.0        53.0           53.0           2.0
13           5.0     2.0        28.0           50.0           2.0
14           1.0     3.0        31.0           48.0           0.0
15           2.0     4.0        35.0           45.0           3.0
16           0.0     5.0        31.0           47.0           2.0
17           4.0     6.0        33.0           46.0           1.0
18           1.0     1.0        70.0           53.0           2.0
19           3.0     2.0        45.0           54.0           2.0
20           4.0     3.0        48.0           51.0           2.0
21           5.0     4.0        54.0           53.0           0.0
22           0.0     5.0        31.0           51.0           0.0
23           2.0     6.0        57.0           49.0           2.0
24           2.0     1.0        43.0           44.0           2.0
25           0.0     2.0        26.0           48.0           2.0
26           4.0     3.0        55.0           50.0           2.0
27           5.0     4.0        43.0           46.0           0.0
28           1.0     5.0        23.0           45.0           2.0
29           3.0     6.0        30.0           46.0           0.0
...          ...     ...         ...            ...           ...
1014         5.0     1.0        34.0           57.0           2.0
1015         2.0     2.0        37.0           52.0           2.0
1016         3.0     3.0        32.0           52.0           1.0
1017         0.0     4.0        35.0           56.0           1.0
1018         4.0     5.0        44.0           53.0           2.0
1019         1.0     6.0        37.0           49.0           2.0
1020         5.0     1.0        33.0           51.0           1.0
1021         3.0     2.0        33.0           52.0           1.0
1022         4.0     3.0        27.0           53.0           1.0
1023         1.0     4.0        43.0           58.0           2.0
1024         2.0     5.0        40.0           53.0           1.0
1025         0.0     6.0        44.0           61.0           2.0
1026         5.0     1.0        38.0           52.0           2.0
1027         2.0     2.0        28.0           49.0           1.0
1028         4.0     3.0        38.0           51.0           1.0
1029         1.0     4.0        34.0           53.0           0.0
1030         3.0     5.0        49.0           54.0           2.0
1031         0.0     6.0        33.0           57.0           2.0
1032         3.0     1.0        31.0           54.0           0.0
1033         5.0     2.0        33.0           51.0           0.0
1034         1.0     3.0        45.0           52.0           2.0
1035         2.0     4.0        51.0           56.0           2.0
1036         4.0     5.0        47.0           55.0           1.0
1037         0.0     6.0        44.0           51.0           2.0
1038         1.0     1.0        52.0           51.0           0.0
1039         3.0     2.0        24.0           53.0           0.0
1040         4.0     3.0        32.0           50.0           0.0
1041         5.0     4.0        35.0           52.0           0.0
1042         0.0     5.0        31.0           52.0           0.0
1043         2.0     6.0        42.0           51.0           0.0

      all_winrate  all_2rate  local_winrate  local_2rate  motor_2rate  \
0            1.56   2.780000           2.00     5.260000    33.330002
1            3.52   9.640000           4.05    17.070000    34.380001
2            3.24   8.060000           4.39    16.670000    34.330002
3            6.88  52.939999           0.00     0.000000    36.669998
4            4.52  21.540001           4.38    37.500000    33.900002
5            2.54   5.050000           2.63     6.670000    36.990002
6            4.59  20.000000           5.18    28.129999    33.330002
7            4.87  26.770000           5.31    36.360001    37.700001
8            4.45  24.420000           4.29    25.000000    36.919998
9            6.74  53.189999           6.20    51.220001    48.529999
10           4.16  20.830000           5.06    29.660000    32.790001
11           4.13  22.620001           4.22    34.779999    32.000000
12           4.09  18.559999           4.17    29.170000    26.670000
13           4.61  31.580000           5.57    38.889999    48.049999
14           5.32  30.160000           6.31    46.669998    41.540001
15           3.69  11.760000           3.92    23.080000    34.849998
16           4.52  24.510000           3.76    23.530001    50.000000
17           6.32  45.630001           6.23    42.860001    40.630001
18           4.34  15.660000           5.03    28.209999    45.590000
19           4.13  22.219999           5.08    29.170000    39.709999
20           4.26  19.270000           5.84    45.160000    31.510000
21           7.49  64.230003           7.88    70.589996    43.590000
22           7.61  58.970001           7.54    50.000000    31.940001
23           5.01  33.700001           3.78    18.520000    36.709999
24           5.30  36.450001           4.71    25.000000    32.259998
25           4.52  21.540001           4.38    37.500000    33.900002
26           3.52   9.640000           4.05    17.070000    34.380001
27           6.72  51.090000           6.78    52.500000    29.850000
28           2.36   0.000000           0.00     0.000000    38.889999
29           6.37  42.619999           8.88    87.500000    34.330002
...           ...        ...            ...          ...          ...
1014         3.79  17.139999           3.14     0.000000    23.879999
1015         4.12  20.180000           4.87    26.670000    19.639999
1016         5.44  35.240002           5.83    42.860001    18.520000
1017         5.68  39.220001           5.85    38.240002    34.150002
1018         4.53  22.770000           5.07    24.389999    44.580002
1019         4.38  24.049999           5.62    46.150002    44.189999
1020         5.71  38.240002           6.13    47.830002    32.000000
1021         5.16  34.849998           4.52    21.740000    33.330002
1022         6.14  44.189999           5.33    33.330002    38.459999
1023         4.35  18.920000           3.88    18.750000    29.870001
1024         6.33  48.320000           7.07    51.720001    33.330002
1025         4.79  27.000000           5.61    33.330002    29.629999
1026         5.95  38.459999           6.46    46.150002    29.110001
1027         5.65  38.740002           4.00    13.330000    42.860001
1028         6.22  40.770000           5.56    31.780001    30.860001
1029         7.09  54.290001           5.71    33.330002    37.080002
1030         4.71  30.000000           5.56    34.880001    41.380001
1031         5.16  28.440001           4.59    26.530001    19.350000
1032         6.96  50.910000           3.67     0.000000    38.270000
1033         6.07  42.060001           6.25    37.500000    37.660000
1034         5.27  29.250000           4.59    29.410000    43.040001
1035         4.13  20.830000           4.89    33.330002    56.180000
1036         5.20  29.700001           5.77    36.169998    35.290001
1037         5.13  29.570000           4.55    13.640000    29.030001
1038         6.87  49.619999           7.31    54.290001    28.360001
1039         6.73  44.290001           5.78    33.330002    38.369999
1040         6.54  47.830002           6.00    43.480000    36.049999
1041         6.50  47.790001           6.63    37.500000    22.370001
1042         6.55  52.759998           6.00    50.000000    32.529999
1043         6.79  48.279999           7.35    58.520000    23.940001

      boat_2rate
0      28.330000
1      30.360001
2      32.259998
3      26.670000
4      40.349998
5      54.840000
6      38.180000
7      34.779999
8      35.820000
9      35.209999
10     40.000000
11     32.650002
12     35.189999
13     40.849998
14     30.879999
15     32.810001
16     30.160000
17     37.840000
18     41.180000
19     33.900002
20     38.810001
21     35.820000
22     32.810001
23     29.690001
24     33.820000
25     40.349998
26     30.360001
27     33.330002
28     38.570000
29     36.959999
...          ...
1014   38.040001
1015   16.670000
1016   10.810000
1017   42.189999
1018   36.049999
1019   35.230000
1020   40.740002
1021   24.360001
1022   29.760000
1023   30.490000
1024   35.369999
1025   23.809999
1026   24.620001
1027   40.320000
1028   37.080002
1029   23.809999
1030   27.450001
1031   21.879999
1032   40.700001
1033   43.279999
1034   21.540001
1035   40.480000
1036   32.860001
1037   47.560001
1038   33.330002
1039   34.849998
1040   33.779999
1041   34.119999
1042   36.900002
1043   33.330002

[1044 rows x 11 columns]

In [6]:
df.head(10)

,rele_truth,teiban,player_age,player_weight,player_level,all_winrate,all_2rate,local_winrate,local_2rate,motor_2rate,boat_2rate
0,3.0,1.0,26.0,50.0,3.0,1.56,2.780000,2.00,5.260000,33.330002,28.330000
1,2.0,2.0,55.0,50.0,2.0,3.52,9.640000,4.05,17.070000,34.380001,30.360001
2,1.0,3.0,57.0,50.0,2.0,3.24,8.060000,4.39,16.670000,34.330002,32.259998
3,4.0,4.0,42.0,47.0,1.0,6.88,52.939999,0.00,0.000000,36.669998,26.670000
4,5.0,5.0,26.0,48.0,2.0,4.52,21.540001,4.38,37.500000,33.900002,40.349998
5,0.0,6.0,22.0,44.0,2.0,2.54,5.050000,2.63,6.670000,36.990002,54.840000
6,5.0,1.0,40.0,52.0,2.0,4.59,20.000000,5.18,28.129999,33.330002,38.180000
7,2.0,2.0,47.0,53.0,2.0,4.87,26.770000,5.31,36.360001,37.700001,34.779999
8,0.0,3.0,25.0,52.0,2.0,4.45,24.420000,4.29,25.000000,36.919998,35.820000
9,4.0,4.0,40.0,53.0,0.0,6.74,53.189999,6.20,51.220001,48.529999,35.209999

In [7]:
dfs = df.iloc[:, 1:].apply(lambda x: (x-x.mean()), axis=0)
dfs.head(10)

,teiban,player_age,player_weight,player_level,all_winrate,all_2rate,local_winrate,local_2rate,motor_2rate,boat_2rate
0,-2.5,-12.25383,-1.914749,1.701149,-3.789445,-31.471178,-3.229895,-28.754023,-0.254242,-6.591112
1,-1.5,16.74617,-1.914749,0.701149,-1.829445,-24.611179,-1.179894,-16.944023,0.795757,-4.561111
2,-0.5,18.74617,-1.914749,0.701149,-2.109445,-26.191177,-0.839895,-17.344023,0.745758,-2.661114
3,0.5,3.74617,-4.914749,-0.298851,1.530555,18.688820,-5.229895,-34.014023,3.085754,-8.251112
4,1.5,-12.25383,-3.914749,0.701149,-0.829445,-12.711178,-0.849895,3.485977,0.315758,5.428886
5,2.5,-16.25383,-7.914749,0.701149,-2.809445,-29.201180,-2.599895,-27.344023,3.405758,19.918888
6,-2.5,1.74617,0.085251,0.701149,-0.759445,-14.251179,-0.049895,-5.884024,-0.254242,3.258888
7,-1.5,8.74617,1.085251,0.701149,-0.479445,-7.481178,0.080105,2.345978,4.115757,-0.141113
8,-0.5,-13.25383,0.085251,0.701149,-0.899445,-9.831179,-0.939895,-9.014023,3.335754,0.898888
9,0.5,1.74617,1.085251,-1.298851,1.390555,18.938820,0.970105,17.205978,14.945755,0.288887

In [8]:
from sklearn.linear_model import LinearRegression

In [11]:
model_lr_std = LinearRegression()
model_lr_std.fit(dfs, df.rele_truth)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
print(model_lr_std.coef_)
print(model_lr_std.intercept_)
print(model_lr_std.score(dfs, df.rele_truth))

[-0.3136385   0.00035617  0.01678238 -0.1296297   0.0086118   0.00559373
 -0.00075812 -0.00039992  0.01233556  0.00615345]
2.5
0.11930384311114184

									

|teiban|player_age|player_weight|player_level|all_winrate|all_2rate|local_winrate|local_2rate|motor_2rate|boat_2rate|
|---|---|---|---|---|---|---|---|---|---|
|-0.3136385|0.00035617 | 0.01678238 | -0.1296297 |0.0086118|0.00559373|-0.00075812| -0.00039992|0.01233556|0.00615345|

In [15]:
model_lr_std.predict(dfs)

array([2.7886567, 2.689396 , 2.376197 , ..., 2.4517438, 2.3028264,
       1.8209693], dtype=float32)